### ISSUE TITLE
Default message

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/product-price#32]
**Is your feature request related to a problem? Please describe.**
Hi! Is it possible to add the default values from the json file? We made a campaign template and the client has to change the prices value from the admin every time a new campaign is added. 

**Describe the solution you'd like**
It would be nice to have a "value" prop for the price that takes control if a site-editor value is not set.

Thanks!

**Comment by iaronaraujo** [comment]
Hi @doruradu ! Yes, it is! You can do so by setting the `message` prop, just keep in mind that it follows the same rules as the site-editor field! We plan on adding more documentation about this prop soon!

**Comment by doruradu** [comment]
Thanks @iaronaraujo !
