### ISSUE TITLE
Product Installments

### ISSUE THREAD

**Issue by stellassantos** [vtex-apps/product-price#59]
**Describe the bug**
Quando o "product-installments" retorna null, quebra o product-summary.shelf.

**To Reproduce**

1. Go to 'https://testecategory--lojaqueroquero.myvtex.com/microondas?_q=microondas&map=ft'
2. See error

**Expected behavior**
Simplesmente não mostrar nada.

**Screenshots**
![image](https://user-images.githubusercontent.com/54483907/108546398-d6a30b80-72c7-11eb-8b0f-6436438b248f.png)
![image](https://user-images.githubusercontent.com/54483907/108546435-dc98ec80-72c7-11eb-9e43-b63bb5aa38db.png)

**Additional context**
Sem o componente, os produtos aparecem.
https://devstella--lojaqueroquero.myvtex.com/forno%20microondas?_q=forno%20microondas&map=ft

**Comment by pscruzzz** [comment]
Estamos analisando o caso via Ticket. Assim que obtiver um retorno, faço o follow up por aqui.

No geral, funciona no Master e em novos workspaces (https://pedrocruz--lojaqueroquero.myvtex.com/microondas?_q=microondas&map=ft), por esse motivo, acredito que o problema esteja atrelado a desenvolvimento com Blocks.

**Comment by pscruzzz** [comment]
The prop `"__unstableProductOriginVtex": true`  should make it work. When the search query is made with `ProductOriginVTEX: true`, the installments array returns full (instead of null).
